### ISSUE TITLE
API changed

### ISSUE THREAD

**Issue by cnoekkii** [hrosseel/belgian_recycle_calendar_creator#4]
![image](https://github.com/hrosseel/belgian_recycle_calendar_creator/assets/17495049/584f672f-e3d1-4f73-9763-5b2ee1ff3b61)

**Comment by paulherbosch** [comment]
just created a fix for that. no longer using the vlaanderen api. fetching all required info straight from recycleapp. should be ok again. apologies for the delay.

**Comment by hrosseel** [comment]
Hi,

Thank you for opening an issue.

It appears that the API has indeed changes. I will create a fix right away.

**Comment by hrosseel** [comment]
Commit [0469616](https://github.com/hrosseel/belgian_recycle_calendar_creator/commit/0469616a477e16b8e5a1122ab1c4f49acedd19df) should have fixed the issue. Please reopen if you're still experiencing issues.
